version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:10-jessie
        environment:
          MYSQL_HOST: localhost
          MYSQL_USER: user
          MYSQL_PASS: user
          MYSQL_DB: tshirtshop
          MYSQL_PORT: 3306
          JWT_KEY: samplejwtkey

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: user
          MYSQL_DATABASE: tshirtshop
          MYSQL_USER: user
          MYSQL_PASSWORD: user

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install MySQL CLI; Import seed;
          command: |
            apt-get update
            apt-get install mysql-client
            mysql -h 127.0.0.1 -u user -puser tshirtshop < database/tshirtshop.sql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd server && yarn install

      - save_cache:
          paths:
            - server/node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}


      # run tests!
      - run: cd server && yarn test
      - store_artifacts:
          path: server/coverage